### PR TITLE
Refresh user signin after updating their profile

### PR DESCRIPTION
**Pull request by jbagga**
See https://github.com/aspnet/templating/pull/199

Identity code has moved to this repo from templating

cc @Eilon

### CODE REVIEW

**Comment by HaoK** [comment]
One small question, is there any reason we prefer RefreshSignIn over just SignIn here?

**Comment by Eilon** [comment]
@HaoK you're the expert, you tell us 😄

**Comment by HaoK** [comment]
Yeah so looks like we added this feature specifically for the templates to use, but never updated them :)

So we should update the rest of the pages in the default UI that are currently using SignIn to use RefreshSignIn

See: https://github.com/aspnet/Identity/blob/dev/src/UI/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs#L94

Today they are hardcoding false after you change the password, which downgrades any persistent remember me cookies to a sesion one.

**Comment by jbagga** [comment]
@HaoK @Eilon I think I should file a new work item for that. It will need some testing

**Comment by HaoK** [comment]
@jbagga sounds fine, the general issue can be summed up as Manage actions lose cookie info (persistent/external login claim) when they call SignInAsync instead of RefreshSignIn

**Comment by jbagga** [comment]
Filed [here](https://github.com/aspnet/Identity/issues/1616)

**Pull request merged**
