### PR TITLE
Added role id equality check in RemoveClaimsAsync

### PR DESCRIPTION
**Pull request by mhowlett**
I think you're forgetting a role id equality check here.

### CODE REVIEW

**Comment by HaoK** [comment]
Ah good catch, mind adding a test so we don't regress this in the future?

**Comment by mhowlett** [comment]
Should be able to find time to do this on the weekend.

**Comment by mhowlett** [comment]
I added an appropriate test (the system seems to have automatically picked that up in this pull request - how clever of it), however it is failing. In the debugger, I can see RemoveClaimAsync is executing as it should, however RoleClaims.Remove(c) doesn't seem to be removing the claims as I thought it would. I don't use Entity Framework, so there is likely a fundamental misunderstanding somewhere on my part... I see dbContext has a method SaveChanges, which I tried calling after attempting to remove the claims, however that made no difference. I think it's better if someone who knows what they're doing with this stuff works out what's going. Sorry, currently rather busy ...

**Comment by HaoK** [comment]
Fair enough, replacing with https://github.com/aspnet/Identity/pull/527

**Pull request closed without merging**
