### PR TITLE
Add generic argument for IdentityRoleClaim

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Identity/issues/855 in a non breaking way (additional base class with the extra generic

### CODE REVIEW

**Comment by HaoK** [comment]
cc @divega

**Comment by aelking** [comment]
Hi there.

Is there any idea on when this will be pulled into the build?

An will this be a patch on the release branch?

This stops alot of customisations with identity working.

Regards

Andy

**Comment by HaoK** [comment]
@divega  says :shipit:

**Comment by HaoK** [comment]
1a0cd3c4d15be988abefd889853b0c6d973db9f4

**Pull request closed without merging**
