### PR TITLE
Added my ASP.NET Identity MongoDB Provider to README.md

### PR DESCRIPTION
**Pull request by alexandre-spieser**
Hi, 

I have implemented an ASP.NET Identity MongoDB Provider and would like to add it to the readme file.

It's covered by more than 800 integration tests and unit tests from the modified Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test test suite.

### CODE REVIEW

**Comment by alexandre-spieser** [comment]
Build error:
```
An assembly specified in the application dependencies manifest (MSBuild.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights', version: '2.0.0'
    path: 'lib/dotnet5.4/Microsoft.ApplicationInsights.dll'
dotnet(5480,0x7fffb8d183c0) malloc: *** error for object 0xffffffffffffffff: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by Eilon** [comment]
@ajcvickers / @HaoK - can you review & merge? Looks alright to me.

**Comment by Eilon** [comment]
Oh actually I guess there's a conflict now, so might need to hand-edit something...

**Comment by blowdart** [comment]
Manually added

**Comment by alexandre-spieser** [comment]
Thanks for this 👍. Have a great day!

**Pull request closed without merging**
