### PR TITLE
Merge release/2.0.0 (without changes)

### LINKED ISSUE #1522: Merge all changes from release/2.0.0 back to dev
I'm not sure https://github.com/aspnet/Identity/pull/1485 made it back into dev. I tried merge the branches and there were a bunch of conflicts. We should look into this closer.

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #1522 

Changes on this branch were already cherry-picked to dev

### CODE REVIEW

**Comment by HaoK** [comment]
Oh oops, I just pushed via cherry pick

**Comment by HaoK** [comment]
79de498dcb740f9930adb2218f75df3babec2ba6

**Comment by natemcmaster** [comment]
😎

**Comment by natemcmaster** [comment]
TIL cherry-picked merge commits don't actually merge branches

**Comment by natemcmaster** [comment]
Looks an actual merge commit this time.

image

**Pull request merged**
