### PR TITLE
Updating .kproj files

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@BrennanConroy__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by suhasj** [comment]
chatted with @BrennanConroy  and this is not needed

**Comment by msotclas** [comment]
Hi __@BrennanConroy__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by divega** [comment]
Was it needed for EF though? @BrennanConroy

**Comment by BrennanConroy** [comment]
I don't think it was for ef. But there are small changes in the identity one.

Sent from my HTC

----- Reply message -----

**Comment by suhasj** [comment]
:shipit:

**Pull request closed without merging**
