### PR TITLE
use WebHost.CreateDefaultBuilder in IdentitySample.Mvc

### PR DESCRIPTION
**Pull request by tugberkugurlu**
so that it picks up the logging config from the `appsettings.json`

### CODE REVIEW

**Comment by HaoK** [comment]
Thanks!

**Comment by HaoK** [comment]
Had to back this out, this introduces cycles in the build dependencies, identity can't depend on AspNetCore

**Comment by tugberkugurlu** [comment]
> Had to back this out, this introduces cycles in the build dependencies, identity can't depend on AspNetCore

That's weird since it's only the sample.

**Comment by HaoK** [comment]
Its a repo circular dependency, AspnetCore is basically last and depends on all the other repos, so nothing in identity can depend on that package

**Pull request merged**
