### PR TITLE
Expose more for extensibility

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Identity/issues/939
https://github.com/aspnet/Identity/issues/969

@divega

### CODE REVIEW

**Comment by HaoK** [comment]
These used to be all public and the unit tests tweak the Managers this way still. They were made internal when we switched to DI to initialize in 3.0.

**Comment by divega** [comment]
Thanks for the information. One more question: what criteria are you using to decide what to make virtual and what not?

**Comment by HaoK** [comment]
I only made the protected methods virtual since there was no harm in letting them tweak those behaviors.  The properties are get/set, so those should be fine non virtual

**Comment by HaoK** [comment]
dbec1c6236ac5cc6bc31db52686259c64c89a7d3

**Pull request closed without merging**
