### PR TITLE
Switch to abstract user factory

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/aspnet/Identity/issues/1722

### CODE REVIEW

**Comment by javiercn** [comment]
@HaoK Can we press pause on this? I don't want to rush https://github.com/aspnet/Identity/issues/1722 in 2.1 as the scope is much bigger and we need time to properly bake it in,

The requirement for 2.1 is that you can use a custom TUser with the default Identity UI. I agreed to get this in for preview2, but I wanted us to revisit it on RC and discuss alternatives.

Can we setup a meeting to discuss this?

**Comment by HaoK** [comment]
Sure we can discuss, but going with an abstract base class should mean that we can fix #1722 however we want later since it won't be a breaking change to add new methods to the base class

**Comment by HaoK** [comment]
I don't think we should try and actually do the full on thing in 2.1 at all

**Comment by javiercn** [comment]
Close? @HaoK

**Pull request closed without merging**
