### PR TITLE
Remove hosting and logging dependencies

### PR DESCRIPTION
**Pull request by HaoK**
Means test code has to provide logging/hosting services, and added null guards for code to compensate for lack of defaults

cc @divega @suhasj

### CODE REVIEW

**Comment by HaoK** [comment]
Fixes https://github.com/aspnet/Identity/issues/431

**Comment by suhasj** [comment]
Can we have a test when the when no logger is passed ? The TestIdentityFactory is registering AddLogging so I feel the current test will always have some value

**Comment by HaoK** [comment]
We could go the other direction on this and require it via [NotNull] instead.  No test necessary that way

**Comment by HaoK** [comment]
Added a new test with null logger to ensure things don't blow up, also cleaned up SignInmanager tests reducing a lot of the duplication with a SetupHelper

**Comment by suhasj** [comment]
This looks good. Better than having the `NotNull` attribute since that would enforce using a logger always which I am not sure would be the right approach

**Comment by HaoK** [comment]
3e9433639021255c1373c9a4bd36c4a511982d18

**Pull request closed without merging**
