### PR TITLE
Shorten folder names

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Identity/issues/1387

Generally drop Microsoft.AspNetCore.Identity from all folder names, resulting structure is basically:

```
Core
Stores
Identity
Specification.Tests
EntityFrameworkCore
Service.*
AspNetCoreCompat
```

@natemcmaster @javiercn @ajcvickers

### CODE REVIEW

**Comment by natemcmaster** [comment]
As long as we are shortening, could we also shorten EntityFrameworkCore to EFCore? aspnet/EntityFrameworkCore itself does this.

**Comment by javiercn** [comment]
@HaoK I'm ok with it. Merge at your discretion once the tests pass

**Comment by HaoK** [comment]
Sure, I'll update to EFCore

**Comment by HaoK** [comment]
If we are going for brevity, why not just EF?

**Comment by natemcmaster** [comment]
To me, EF usually implies EF6

**Comment by HaoK** [comment]
That might be more of an issue in the EF repo, but whatever EFCore is fine

**Comment by natemcmaster** [comment]
Honestly fine either way. Whatever you think makes more sense.

:shipit: when CI passes

**Comment by HaoK** [comment]
85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c

**Pull request closed without merging**
