### PR TITLE
Switch back to netstandard2.0

### PR DESCRIPTION
**Pull request by HaoK**
Core identity looks straight forward

@javiercn can you update the new service stuff in this PR, there appears to be issues with your cryptohelpers:

CryptographyHelpers.cs(46,62): error CS1503: Argument 1: cannot convert from 'int' to 'string' [C:\GitHub\Identity\src\Microsoft.AspNetCore.Identity.Service.Core\Microsoft.AspNetCore.Identity.Service.Core.csproj]

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
I think the mvc updates have been merged, this is unblocked.

**Comment by pranavkm** [comment]
@javiercn can you fix the crypto compilation issues here?

**Comment by javiercn** [comment]
Merged https://github.com/aspnet/Identity/commit/45f9780d32bc83a0ce8b7de3d6620427672df9c0

**Comment by HaoK** [comment]
@JunTaoLuo so is MVC not done yet, were we supposed to not merge this change yet?

**Comment by JunTaoLuo** [comment]
Yea I was under the impression MVC was still blocked. @ryanbrandenburg @NTaylorMullen

**Comment by NTaylorMullen** [comment]
MVC isn't testing on desktop due to preserve compilation context issues. Aka, we've worked around the break for now.

**Pull request closed without merging**
