### PR TITLE
Remove ClaimsPrincipal extensions, replace with instance

### PR DESCRIPTION
**Pull request by HaoK**
- Removes static GetUserId/GetUserName/IsSigned in from ClaimsPrincipal
- Replaced with SignInManager.GetUserId/GetUserName/IsSignedIn/GetUserAsync which accomplish the same thing but eliminates statics, and instead respect IdentityOptions.ClaimsIdentity for the claim types
- Cleaned up SecurityStamp validator to use SignInManager/IOptions as a service

cc @divega @blowdart @rustd

### CODE REVIEW

**Comment by HaoK** [comment]
Fixes https://github.com/aspnet/Identity/issues/663

**Comment by rustd** [comment]
@HaoK Can you please make the changes in the templates repo for these new APIs as well?

**Comment by rustd** [comment]
Can you post to the announcements repo as well about this change.

**Comment by HaoK** [comment]
Move GetUserId/GetUserName to UserManager

**Comment by HaoK** [comment]
2dade94404d3198b19e6af9083b410287e11314f

**Pull request closed without merging**
