### PR TITLE
Remove CancellationToken from Manager APIs

### PR DESCRIPTION
**Pull request by HaoK**
Only the Stores continue to take CancellationToken, but they are no longer optional 

Fixes https://github.com/aspnet/Identity/issues/355

cc @divega @suhasj

### CODE REVIEW

**Comment by suhasj** [comment]
I thought we were removing the cancellation token from SigninManager only ? Isnt that the case ?

**Comment by HaoK** [comment]
Our managers are scoped anyways, so it seems safe to just have them depend on HttpContextAccessor in the ctor as well, @divega thoughts?

**Comment by divega** [comment]
@HaoK @suhasj Adding the HttpContextAccessor dependency seems fine. It was my thought was well when I realized that only SignInManager had it. A couple of points:

1. I believe the removal of CancellationToken from methods of some of the interfaces adds an implicit assumption that the implementaiton of the interface will have access to the CancelationToken from the HttpContext. This might be ok. I just want us to think it through.

2. @yishaigalatzer mentioned that there were potentially multiple sources of cancellation. If you haven't already, could you follow up and make sure that listening to the CancellationToken in HttpContext is enough?

Otherwise it looks :shipit: to me.

**Comment by HaoK** [comment]
@divega All of the interface implementations can be activated from DI, and as such they can all use HttpContextAccessor to get access to the cancellation token if they desire (we don't do this today, but custom implementations could if they want)

**Comment by divega** [comment]
> we don't do this today
@HaoK is there anything inherently cancellable that we are missing? BTW, I noticed that you left the CancellationToken in place for the messaging API, which seems the best choice.

**Comment by HaoK** [comment]
I'm not really sure, to be honest, we never got around to writing any tests that were exercising the cancellation tokens anyways...  So I'm glad we got rid of them for that reason alone :)

**Comment by divega** [comment]
Ok. I took a look at some of the interfaces, e.g. validation. If none of the default implementations of the interfaces use databases or need to potentially make calls over the network, I think it is fine to remove the CancelationToken from the methods. As you said, customer implementations can get the IHttpContextAccessor if needed. 

What about the second concern? Can you follow up with @yishaigalatzer?

**Comment by HaoK** [comment]
Sure I'll can follow up with Yishai

**Pull request merged**
