### PR TITLE
Add missing doc comments

### PR DESCRIPTION
**Pull request by HaoK**
Also removes the nowarn for missing doc comments

@blowdart @divega

### CODE REVIEW

**Comment by blowdart** [comment]
Good lord, Hao has written doc comments :D

**Comment by HaoK** [comment]
Copy pasted yours mostly :)  Fixes https://github.com/aspnet/Identity/issues/872

**Comment by HaoK** [comment]
Is the content acceptable enough for a furry little friend? @blowdart

**Comment by blowdart** [comment]
:shipit:

**Comment by HaoK** [comment]
ec4c08d11a00ec9b4dd8c22ef13a4950cb70901e

**Pull request closed without merging**
