### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aguacongas**
Hi guys,
Today I propose you Aguacongas.Identy.Redis, my implemention of APS.NET Identity Redis Provider

### CODE REVIEW

**Comment by Eilon** [comment]
@aguacongas thanks for the PR! @ajcvickers / @HaoK  - does this look good to merge?

**Comment by ajcvickers** [comment]
@blowdart @HaoK Not sure whether you guys do any sanity checks on external references like this?

**Comment by blowdart** [comment]
Not really no. We ought to add a disclaimer to these links.

**Comment by ajcvickers** [comment]
@blowdart I'll copy the one we have in EF.

**Pull request merged**
