### PR TITLE
Add + to allowed username characters by default

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Identity/issues/742

cc @divega @blowdart

### CODE REVIEW

**Comment by divega** [comment]
:shipit: I am fine with taking this change because it seems to be an improvement. It would be great if we had more of an objective way to decide what characters to allow by default, e.g. something based on what the most popular email servers/services out there allow.

**Comment by MaximRouiller** [comment]
@divega 

**Gmail**: letter, numbers, `.`, `+`

Don't know about other email providers.

**Comment by divega** [comment]
Gmail actually allows letters, numbers and periods but not plus sign. Of course other systems do allow the later. Anyway, the change is in and I don't think we need to proactively revisit the list until we get a similar request,  if we ever do.

**Comment by MaximRouiller** [comment]
Gmail does not allow + when registering but any emails on Gmail containing the + sign will be valid.

They call it email "tagging" or something like that.

**Pull request merged**
