### PR TITLE
Injecting ILogger via DI

### PR DESCRIPTION
**Pull request by suhasj**
@divega @HaoK 

Changes
- Removed ILoggerFactory to inject ILogger<T>
- updated tests to inject mock logger instead loggerfactory
- fixed formatting in documents which messed up the diffs

### CODE REVIEW

**Comment by HaoK** [comment]
Why is every line touched in these files?

**Comment by suhasj** [comment]
I formatted the document using the latest VS and this happened. This looks ugly, I see if I can fix it

**Comment by suhasj** [comment]
Fixed the PR. Should be more readable now

**Comment by HaoK** [comment]
Mockhelpers formatting still messed up

**Comment by HaoK** [comment]
:Shipit:

**Pull request closed without merging**
