### PR TITLE
Use the correct logging category inside RegisterModel

### PR DESCRIPTION
**Pull request by huysentruitw**
This pull-request fixes the logging category when messages are logged from the ASP.NET Identity UI Register page. Should be a non-breaking change.

### CODE REVIEW

**Comment by blowdart** [comment]
@Eilon Do you want this merged for 2.2?

**Comment by Eilon** [comment]
@blowdart I think that would be a good idea.

**Comment by blowdart** [comment]
@mkArtakMSFT can you ok @javiercn to do this please?

**Comment by javiercn** [comment]
I'll merge it as soon as the CI passes

**Comment by blowdart** [comment]
Thank you sir

**Comment by javiercn** [comment]
Done

**Pull request merged**
