### PR TITLE
Using file lock when reading file

### PR DESCRIPTION
**Pull request by suhasj**
@divega I had missed out on using file lock when reading from the file

### CODE REVIEW

**Comment by suhasj** [comment]
@HaoK

**Comment by suhasj** [comment]
Description: The functional tests have a file logger that logs messages to a file and reads from it in the assert statements. I had used `lock` while writing but not while reading causing the tests to fail. I verified that tests run fine after these changes

**Comment by pranavkm** [comment]
:shipit:

**Comment by suhasj** [comment]
Merge thanks @pranavkm

**Pull request merged**
