### PR TITLE
 remove roleType while make UserOnlyStore

### PR DESCRIPTION
**Pull request by KhuongNtrd**

### CODE REVIEW

**Comment by HaoK** [comment]
Thanks for finding this issue, I've filed an issue to track https://github.com/aspnet/Identity/issues/1480

**Comment by Vertigo093i** [comment]
I suggest that the other branch of the `if` expression also needs a similar fix. By removing `roleType` parameter and replacing `UserStore<,,,>` with `UserOnlyStore<,,>`.

**Comment by HaoK** [comment]
Ah yeah, good point, missing a test for that branch

**Comment by HaoK** [comment]
Fixed in dev (2.1) via https://github.com/aspnet/Identity/pull/1481, we will consider porting the fix to a 2.0.x patch if there's demand

**Pull request closed without merging**
