### PR TITLE
Enabling NuGetPackageVerifier

### PR DESCRIPTION
**Pull request by ajaybhargavb**
@Eilon

### CODE REVIEW

**Comment by divega** [comment]
Does the test pass with this package? If no, and the package description is required, please see #409 for the right strings.

**Comment by ajaybhargavb** [comment]
It passes. Note that the `RequiredPackageMetadataRule` is currently not being run.It will be enabled later.

**Comment by divega** [comment]
Thanks. Looks :shipit: to me.

**Comment by Eilon** [comment]
:shipit:

**Pull request merged**
