### PR TITLE
Bump Microsoft.AspNetCore.Identity.Specification.Tests to net452

### PR DESCRIPTION
**Pull request by cesarbs**
Reacting to https://github.com/aspnet/Testing/commit/a31400b7377909f5f8ae9f9496a0a8ffb0496a6f.

### CODE REVIEW

**Comment by cesarbs** [comment]
It's broken.

**Comment by cesarbs** [comment]
Ugly hack in .csproj is ugly. The trouble is TaskCache's sources use `#if NET451`.

@natemcmaster There's no cleaner way around this, right?

**Comment by natemcmaster** [comment]
Let's update the c# in the  taskcache package to include `#if NET451 || NET452`

**Comment by JunTaoLuo** [comment]
Yea the TaskCache.Sources packages should be the one updated not the .csproj here.

**Comment by cesarbs** [comment]
Reverted the hack in the .csproj file.

**Pull request merged**
