### PR TITLE
Add support for proof of key for code exchange

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by javiercn** [comment]
The spec is here: https://tools.ietf.org/html/rfc7636
In essence:
* The client sends a code challenge, which is the sha256 of a high entropy value on the authorize request.
* The server associates that value with the issued code
* The client sends the original high entropy value to the server on the token request.
* The server hashes that value, base64url encodes it and compares it against the challenge associate with the code.
* If the computed challenge matches the original challenge we emit tokens, otherwise we fail.

**Comment by Tratcher** [comment]
Should we be adding support for this in our clients?

**Comment by leastprivilege** [comment]
PKCE is for desktop/mobile native clients.

**Comment by danroth27** [comment]
Fixes https://github.com/aspnet/Identity/issues/1205

**Pull request closed without merging**
