### PR TITLE
Update IdentityServiceCollectionExtensions.cs

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fix Copy/paste error from `AddIdentity<TUser, TRole>`

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Is CI failing because VS is showing:
XML comment has cref attribute 'AddRoles{TRole}' that could not be resolved

**Comment by HaoK** [comment]
Yeah its a method on identity builder, this should resolve: `<see cref="IdentityBuilder.AddRoles{TRole}"/>`

**Comment by HaoK** [comment]
Looks good do you have permissions to squash/merge this PR Rick?  You can do the honors if so

**Comment by Rick-Anderson** [comment]
@HaoK no I don't and want to keep it that way.

**Comment by HaoK** [comment]
np, thanks @Rick-Anderson !

**Pull request merged**
