### PR TITLE
Enabled xml doc generation

### PR DESCRIPTION
**Pull request by ajaybhargavb**
@NTaylorMullen

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by MaximRouiller** [comment]
What is ADX?

**Comment by MaximRouiller** [comment]
Also... `NuGetPackageVerifier.json`? :smile: look like a fun tool.

Links? :stuck_out_tongue:

**Comment by ajaybhargavb** [comment]
ADX is the team responsible for shipping AspNetCore packages. This is the tool that verifies the NuGet packages. https://github.com/aspnet/DnxTools/tree/dev/src/NuGetPackageVerifier

**Comment by MaximRouiller** [comment]
You guys should share it with the world.

aspnet/DnxTools/issues/24

**Pull request merged**
