### PR TITLE
House Cleaning - Spell check and grammar.

### PR DESCRIPTION
**Pull request by bchavez**
House Cleaning - Spell check and grammar. :shower:

:ear_of_rice: :stew: ***["Out here in the fields... I fight for my meals... It's only teenage wasteland..."](https://www.youtube.com/watch?v=IXWNSb4nUDY)***

### CODE REVIEW

**Comment by bchavez** [comment]
Related PR #1305. I see now both PRs contain typeo fixes (some are the same, some are not). Let me know and I can cherry pick / include PR #1305 to avoid a possible merge conflict.

**Comment by HaoK** [comment]
@bchavez can you update the tests that are failing due to the log message changes as well?  The typos are likely in the tests as well

**Comment by bchavez** [comment]
@HaoK , Sorry, I didn't realize the failing test was my fault. I've rebased the PR and fixed the failing test. The AppVeyor tests pass but I'm not sure what's wrong with Travis CI.

**Comment by HaoK** [comment]
Thanks @bchavez !

**Pull request merged**
