### PR TITLE
Friendlier ToString

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Identity/issues/183

@divega @blowdart @rustd Thoughts on the text?  I wasn't sure if the "Role/User" prefix was necessary, shrug...

### CODE REVIEW

**Comment by blowdart** [comment]
I wouldn't add them. It's not like if you call toString on a date you get "Date: 08 June 2015"

**Comment by HaoK** [comment]
Ok so just print out the name by itself?

**Comment by blowdart** [comment]
Yup

**Comment by HaoK** [comment]
4e5bba35da259fa79a90426ed02a72f0c03ec861

**Pull request closed without merging**
