### PR TITLE
Fix doc comments

### PR DESCRIPTION
**Pull request by HaoK**
@divega @blowdart @Eilon

### CODE REVIEW

**Comment by divega** [comment]
@HaoK thanks! Could you remove CS1591 warning from Microsoft.AspNetCore.Identity/project.json and Microsoft.AspNetCore.Identity.EntityFrameworkCore/project.json and see what happens?

**Comment by HaoK** [comment]
Still missing some doc comments

**Comment by divega** [comment]
Can't build it right now :sad: How much is missing?

**Comment by HaoK** [comment]
Not a ton, maybe on the order of 6-10 methods, none of them are very important looking

**Comment by divega** [comment]
I think there a couple of new comments in https://github.com/aspnet/Identity/issues/869. Maybe we should wait until @xperiandri finishes reviewing? :smile:

**Comment by divega** [comment]
Other than that LGTM.

**Comment by divega** [comment]
@HaoK is it just `IdentityCookieOptions` that is missing some comments?

**Comment by Eilon** [comment]
Time has pretty much run out, so please get in whatever you can; the rest will have to wait.

**Comment by HaoK** [comment]
Ok I will just check this in as is, we can fix the rest in 1.0.1

**Comment by HaoK** [comment]
7b3b3627957404fe9083268929dd5589f7a26d1b

**Pull request closed without merging**
