### PR TITLE
Added FindByPhoneNumberAsync 

### PR DESCRIPTION
**Pull request by SharePointRadi**
This PR addresses the FindByPhoneNumberAsync functionality request in UserStore and UserManager, and the IPhoneNumberStore interface
Related issue https://github.com/aspnet/Identity/issues/704

I am still trying to get xunit to run normally to commit the unit tests as well...

### CODE REVIEW

**Comment by SharePointRadi** [comment]
I added a unit test to validate that we can find users by phone number.

**Comment by divega** [comment]
@rustd, @HaoK, @blowdart I cannot recall what we decided in triage about this PR. 

In any case, if we wanted to take it I am not sure about the name of the method. Across a few components we are pretty consistently using the `Find` prefix for methods that return zero or one instances based on a condition or key. This is more of a `GetUsersByPhoneNumber()` I think.

**Comment by SharePointRadi** [comment]
I am happy to follow through any decisions you guys make and amend it

**Comment by HaoK** [comment]
We decided that we don't think this is appropriate as general functionality since apps can do this easily themselves.

**Pull request closed without merging**
